baseURL = ""
title = "temporaerhaus"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
languageCode = "de-DE"
theme = "twentysixteen"
paginate = 10
enableRobotsTXT = true

[params]
siteLogoUrl = "/spaceicons/logo.svg"

[frontmatter]
date = [":filename", ":default"]

[languages]
  [languages.de]
    weight = 1
    languageName = "Deutsch"

    [languages.de.permalinks]
      posts = "/:slug"
      post = "/:slug"
      page = "/:slug"
      pages = "/:slug"
      category = "/category/:slug"
      categories = "/category/:slug"
      tag = "/tag/:slug"
      tags = "/tag/:slug"
      group = "/gruppen/:slug"
      groups = "/gruppen/:slug"
      make = "/make/:slug"

    [[languages.de.menu.main]]
      identifier = "das-haus"
      name = "Das Haus"
      url = "/das-haus/"
      weight = -110

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "tour"
      name = "Virtuelle Tour"
      url = "/tour/"

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "Umzug"
      name = "Umzug"
      url = "/umzug/"

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "logos-und-bilder"
      name = "Logos und Bilder"
      url = "/presse-logos-und-bilder/"

    [[languages.de.menu.main]]
      parent = "das-haus"
      identifier = "wiki"
      name = "Wiki"
      url = "https://wiki.temporaerhaus.de"

    [[languages.de.menu.main]]
      identifier = "make"
      name = "Möglichkeiten"
      url = "/make/"
      weight = -100

    [[languages.de.menu.main]]
      parent = "make"
      identifier = "bibliothek"
      name = "Bibliothek"
      url = "/bibliothek/"

    [[languages.de.menu.main]]
      identifier = "groups"
      name = "Gruppen"
      url = "/gruppen/"
      weight = -90

    [[languages.de.menu.main]]
      parent = "groups"
      identifier = "jhlab"
      name = "Jugend hackt Lab"
      url = "/category/jugend-hackt-lab/"

    [[languages.de.menu.main]]
      identifier = "termine-und-oeffnungszeiten"
      name = "Events & Kalender"
      url = "/termine-und-oeffnungszeiten/"
      weight = -80

    [[languages.de.menu.main]]
      identifier = "ueber-uns"
      name = "Über uns"
      url = "/das-haus/"
      weight = -70

    [[languages.de.menu.main]]
      parent = "ueber-uns"
      identifier = "history"
      name = "Geschichte"
      url = "/geschichte/"
      weight = -76

    [[languages.de.menu.main]]
      parent = "ueber-uns"
      identifier = "verein"
      name = "Der Verein"
      url = "/verein/"
      weight = -75

#    [[languages.de.menu.main]]
#      parent = "ueber-uns"
#      identifier = "sponsors"
#      name = "Unterstützer*innen & Sponsoren"
#      url = "#"
#      weight = -74

    [[languages.de.menu.main]]
      parent = "ueber-uns"
      identifier = "spenden"
      name = "Spenden"
      url = "/spenden/"
      weight = -73

    [[languages.de.menu.main]]
      parent = "ueber-uns"
      identifier = "presse"
      name = "Presseberichte"
      url = "/presse/"
      weight = -72

    [[languages.de.menu.main]]
      parent = "ueber-uns"
      identifier = "kontakt"
      name = "Kontakt"
      url = "/kontakt/"
      weight = -70

    [[languages.de.menu.footer]]
      identifier = "kontakt"
      name = "Kontakt"
      url = "/kontakt/"
      weight = -100

    [[languages.de.menu.footer]]
      identifier = "privacy"
      name = "Datenschutzerklärung"
      url = "/datenschutzerklaerung/"

    [[languages.de.menu.footer]]
      identifier = "impressum"
      name = "Impressum"
      url = "/impressum/"

    [[languages.de.menu.footer]]
      identifier = "rsslink"
      name = "RSS Feed"
      url = "/posts/index.xml"

    [[languages.de.menu.social]]
      name = "temporaerhaus auf Mastodon"
      url = "https://chaos.social/@temporaerhaus"

    [[languages.de.menu.social]]
      name = "temporaerhaus auf Twitter"
      url = "https://twitter.com/temporaerhaus"

    [[languages.de.menu.social]]
      name = "temporaerhaus auf GitHub"
      url = "https://github.com/temporaerhaus"

    [[languages.de.menu.social]]
      name = "temporaerhaus auf YouTube"
      url = "https://www.youtube.com/temporaerhaus"

    [[languages.de.menu.social]]
      name = "temporaerhaus auf Instagram"
      url = "https://www.instagram.com/temporaerhaus/"

  [languages.en]
    weight = 2
    languageCode = "en-us"
    languageName = "English"

    [languages.en.permalinks]
      posts = "/:slug"
      post = "/:slug"
      page = "/:slug"
      pages = "/:slug"
      category = "/category/:slug"
      categories = "/category/:slug"
      tag = "/tag/:slug"
      tags = "/tag/:slug"
      group = "/groups/:slug"
      groups = "/groups/:slug"
      make = "/make/:slug"

    [[languages.en.menu.main]]
      identifier = "das-haus"
      name = "The House"
      url = "/en/das-haus/"
      weight = -110

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "tour"
      name = "Virtual Tour"
      url = "/en/tour/"

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "umzug"
      name = "Moving"
      url = "/en/umzug/"

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "logos-und-bilder"
      name = "Logos and Photos"
      url = "/en/presse-logos-und-bilder/"

    [[languages.en.menu.main]]
      parent = "das-haus"
      identifier = "wiki"
      name = "Wiki"
      url = "https://wiki.temporaerhaus.de"

    [[languages.en.menu.main]]
      identifier = "make"
      name = "Do stuff"
      url = "/make/"
      weight = -100

    [[languages.en.menu.main]]
      parent = "make"
      identifier = "bibliothek"
      name = "Library"
      url = "/en/bibliothek/"

    [[languages.en.menu.main]]
      identifier = "groups"
      name = "Groups"
      url = "/en/groups/"
      weight = -90

    [[languages.en.menu.main]]
      parent = "groups"
      identifier = "jhlab"
      name = "Jugend hackt Lab"
      url = "/en/category/jugend-hackt-lab/"

    [[languages.en.menu.main]]
      identifier = "termine-und-oeffnungszeiten"
      name = "Events and Calendar"
      url = "/en/termine-und-oeffnungszeiten/"
      weight = -80

    [[languages.en.menu.main]]
      identifier = "about-us"
      name = "About us"
      url = "/en/das-haus/"
      weight = -70

    [[languages.en.menu.main]]
      parent = "about-us"
      identifier = "history"
      name = "History"
      url = "/en/geschichte/"
      weight = -76

    [[languages.en.menu.main]]
      parent = "about-us"
      identifier = "verein"
      name = "The Verein"
      url = "/en/verein/"
      weight = -75

#    [[languages.en.menu.main]]
#      parent = "about-us"
#      identifier = "sponsors"
#      name = "Supporters & Sponsors"
#      url = "#"
#      weight = -74

    [[languages.en.menu.main]]
      parent = "about-us"
      identifier = "donation"
      name = "Donate"
      url = "/en/spenden/"
      weight = -73

    [[languages.en.menu.main]]
      parent = "about-us"
      identifier = "press"
      name = "Press"
      url = "/en/presse/"
      weight = -72

    [[languages.en.menu.main]]
      parent = "about-us"
      identifier = "kontakt"
      name = "Contact"
      url = "/en/kontakt/"
      weight = -71

    [[languages.en.menu.footer]]
      identifier = "kontakt"
      name = "Contact"
      url = "/en/kontakt/"
      weight = -100

    [[languages.en.menu.footer]]
      identifier = "privacy"
      name = "Privacy Policy"
      url = "/en/datenschutzerklaerung/"

    [[languages.en.menu.footer]]
      identifier = "impressum"
      name = "Impressum"
      url = "/en/impressum/"

    [[languages.en.menu.footer]]
      identifier = "rsslink"
      name = "RSS Feed"
      url = "/en/posts/index.xml"

    [[languages.en.menu.social]]
      name = "temporaerhaus on Mastodon"
      url = "https://chaos.social/@temporaerhaus"

    [[languages.en.menu.social]]
      name = "temporaerhaus on Twitter"
      url = "https://twitter.com/temporaerhaus"

    [[languages.en.menu.social]]
      name = "temporaerhaus on GitHub"
      url = "https://github.com/temporaerhaus"

    [[languages.en.menu.social]]
      name = "temporaerhaus on YouTube"
      url = "https://www.youtube.com/temporaerhaus"

    [[languages.en.menu.social]]
      name = "temporaerhaus on Instagram"
      url = "https://www.instagram.com/temporaerhaus/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
